name: Ypenburg
layout_spectrum: 0.780405
typography_spectrum: 0.871638226788491
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7061908338218927
  lightness: 0.6067466146778315
  saturation: 0.6304710772819817
  rhythmicContrast: 0.40844056056812406
title: >-
  Ypenburg, Den Haag. Nieuws, linkjes, foto's van & over de wijk en meer. Voor
  bewoners, ondernemers en bezoekers. Door @fabiobruna Onafhankelijk &
  vrijwillig.
author:
  name: 'Fabio Bruna '
  url: ''
  email: ''
content_rating:
  adult: false
