layout_spectrum: 0.5108707756735384
typography_spectrum: 0.06326022557914257
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.4962320865597576
  lightness: 0.06375631527043879
  saturation: 0.5710320570506155
  rhythmicContrast: 0.6823621655348688
name: Ypenburg
opengraph:
  type: ''
  appId: ''
title: >-
  Ypenburg, Den Haag. Nieuws, linkjes, foto's van & over de wijk en meer. Voor
  bewoners, ondernemers en bezoekers. Door @fabiobruna Onafhankelijk &
  vrijwillig.
author:
  name: 'Fabio Bruna '
  url: ''
  email: ''
content_rating:
  adult: false
